# 

development:
  adapter: mysql
  encoding: utf8
  database: discharged_development
  username: root
  password:
  socket: /tmp/mysql.sock

test: &TEST
  adapter: mysql
  encoding: utf8
  #collation: utf8_general_ci
  reconnect: false
  database: discharged_test
  pool: 5
  username: root
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: discharged_production
  username: 
  password:

                           