require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActionProgramsController do

  # This should return the minimal set of attributes required to create a valid
  # ActionProgram. As you add validations to ActionProgram, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActionProgramsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all action_programs as @action_programs" do
      action_program = ActionProgram.create! valid_attributes
      get :index, {}, valid_session
      assigns(:action_programs).should eq([action_program])
    end
  end

  describe "GET show" do
    it "assigns the requested action_program as @action_program" do
      action_program = ActionProgram.create! valid_attributes
      get :show, {:id => action_program.to_param}, valid_session
      assigns(:action_program).should eq(action_program)
    end
  end

  describe "GET new" do
    it "assigns a new action_program as @action_program" do
      get :new, {}, valid_session
      assigns(:action_program).should be_a_new(ActionProgram)
    end
  end

  describe "GET edit" do
    it "assigns the requested action_program as @action_program" do
      action_program = ActionProgram.create! valid_attributes
      get :edit, {:id => action_program.to_param}, valid_session
      assigns(:action_program).should eq(action_program)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ActionProgram" do
        expect {
          post :create, {:action_program => valid_attributes}, valid_session
        }.to change(ActionProgram, :count).by(1)
      end

      it "assigns a newly created action_program as @action_program" do
        post :create, {:action_program => valid_attributes}, valid_session
        assigns(:action_program).should be_a(ActionProgram)
        assigns(:action_program).should be_persisted
      end

      it "redirects to the created action_program" do
        post :create, {:action_program => valid_attributes}, valid_session
        response.should redirect_to(ActionProgram.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved action_program as @action_program" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActionProgram.any_instance.stub(:save).and_return(false)
        post :create, {:action_program => {}}, valid_session
        assigns(:action_program).should be_a_new(ActionProgram)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ActionProgram.any_instance.stub(:save).and_return(false)
        post :create, {:action_program => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested action_program" do
        action_program = ActionProgram.create! valid_attributes
        # Assuming there are no other action_programs in the database, this
        # specifies that the ActionProgram created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ActionProgram.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => action_program.to_param, :action_program => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested action_program as @action_program" do
        action_program = ActionProgram.create! valid_attributes
        put :update, {:id => action_program.to_param, :action_program => valid_attributes}, valid_session
        assigns(:action_program).should eq(action_program)
      end

      it "redirects to the action_program" do
        action_program = ActionProgram.create! valid_attributes
        put :update, {:id => action_program.to_param, :action_program => valid_attributes}, valid_session
        response.should redirect_to(action_program)
      end
    end

    describe "with invalid params" do
      it "assigns the action_program as @action_program" do
        action_program = ActionProgram.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActionProgram.any_instance.stub(:save).and_return(false)
        put :update, {:id => action_program.to_param, :action_program => {}}, valid_session
        assigns(:action_program).should eq(action_program)
      end

      it "re-renders the 'edit' template" do
        action_program = ActionProgram.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ActionProgram.any_instance.stub(:save).and_return(false)
        put :update, {:id => action_program.to_param, :action_program => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested action_program" do
      action_program = ActionProgram.create! valid_attributes
      expect {
        delete :destroy, {:id => action_program.to_param}, valid_session
      }.to change(ActionProgram, :count).by(-1)
    end

    it "redirects to the action_programs list" do
      action_program = ActionProgram.create! valid_attributes
      delete :destroy, {:id => action_program.to_param}, valid_session
      response.should redirect_to(action_programs_url)
    end
  end

end
